spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G9FYDjpSWetZoAELrtU
      secret-key: MboRrDW02oHzGgcwVL9eFbyancvRcZ
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: mymall1
  application:
    name: mymall-third-party

server:
  port: 30000