spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        - id: product_route
          uri: lb://mymall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mymall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://mymall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mymall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_root
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mymall_host_route
          uri: lb://mymall-product
          predicates:
            - Host=mymall.com,item.mymall.com

        - id: mymall_search_route
          uri: lb://mymall-search
          predicates:
            - Host=search.mymall.com

        - id: mymall_auth_route
          uri: lb://mymall-auth-server
          predicates:
            - Host=auth.mymall.com

        - id: mymall_cart_route
          uri: lb://mymall-cart
          predicates:
            - Host=cart.mymall.com

        - id: mymall_order_route
          uri: lb://mymall-order
          predicates:
            - Host=order.mymall.com

        - id: mymall_member_route
          uri: lb://mymall-member
          predicates:
            - Host=member.mymall.com

        - id: mymall_seckill_route
          uri: lb://mymall-seckill
          predicates:
            - Host=seckill.mymall.com

# 前端项目：/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree
#精确的路由放在高优先级，模糊的路由放在低优先级
